// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.32.1
// source: zkpVerification.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "zkpVerification";

export interface VerifyClauseInclusionRequest {
  agreementId: string;
  clauseSetHash: string;
  commitment: string;
}

export interface VerifyClauseInclusionResponse {
  success: boolean;
  message: string;
  isValid: boolean;
}

export interface BGExpiryCheckRequest {
  bgExpiry: string;
  POEndDate: string;
  NDays: string;
  bgExpiryHash: string;
}

export interface BGExpiryCheckResponse {
  success: boolean;
  message: string;
  isValid: boolean;
}

export interface AmountWithinRangeRequest {
  invoiceTotal: string;
  poBalance: string;
  poBalanceHash: string;
}

export interface AmountWithinRangeResponse {
  success: boolean;
  message: string;
  isValid: boolean;
}

function createBaseVerifyClauseInclusionRequest(): VerifyClauseInclusionRequest {
  return { agreementId: "", clauseSetHash: "", commitment: "" };
}

export const VerifyClauseInclusionRequest: MessageFns<VerifyClauseInclusionRequest> = {
  encode(message: VerifyClauseInclusionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.agreementId !== "") {
      writer.uint32(10).string(message.agreementId);
    }
    if (message.clauseSetHash !== "") {
      writer.uint32(18).string(message.clauseSetHash);
    }
    if (message.commitment !== "") {
      writer.uint32(26).string(message.commitment);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyClauseInclusionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyClauseInclusionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.agreementId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clauseSetHash = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.commitment = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VerifyClauseInclusionRequest {
    return {
      agreementId: isSet(object.agreementId) ? globalThis.String(object.agreementId) : "",
      clauseSetHash: isSet(object.clauseSetHash) ? globalThis.String(object.clauseSetHash) : "",
      commitment: isSet(object.commitment) ? globalThis.String(object.commitment) : "",
    };
  },

  toJSON(message: VerifyClauseInclusionRequest): unknown {
    const obj: any = {};
    if (message.agreementId !== "") {
      obj.agreementId = message.agreementId;
    }
    if (message.clauseSetHash !== "") {
      obj.clauseSetHash = message.clauseSetHash;
    }
    if (message.commitment !== "") {
      obj.commitment = message.commitment;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VerifyClauseInclusionRequest>, I>>(base?: I): VerifyClauseInclusionRequest {
    return VerifyClauseInclusionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyClauseInclusionRequest>, I>>(object: I): VerifyClauseInclusionRequest {
    const message = createBaseVerifyClauseInclusionRequest();
    message.agreementId = object.agreementId ?? "";
    message.clauseSetHash = object.clauseSetHash ?? "";
    message.commitment = object.commitment ?? "";
    return message;
  },
};

function createBaseVerifyClauseInclusionResponse(): VerifyClauseInclusionResponse {
  return { success: false, message: "", isValid: false };
}

export const VerifyClauseInclusionResponse: MessageFns<VerifyClauseInclusionResponse> = {
  encode(message: VerifyClauseInclusionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.isValid !== false) {
      writer.uint32(24).bool(message.isValid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyClauseInclusionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyClauseInclusionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isValid = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VerifyClauseInclusionResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      isValid: isSet(object.isValid) ? globalThis.Boolean(object.isValid) : false,
    };
  },

  toJSON(message: VerifyClauseInclusionResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.isValid !== false) {
      obj.isValid = message.isValid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VerifyClauseInclusionResponse>, I>>(base?: I): VerifyClauseInclusionResponse {
    return VerifyClauseInclusionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyClauseInclusionResponse>, I>>(
    object: I,
  ): VerifyClauseInclusionResponse {
    const message = createBaseVerifyClauseInclusionResponse();
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    message.isValid = object.isValid ?? false;
    return message;
  },
};

function createBaseBGExpiryCheckRequest(): BGExpiryCheckRequest {
  return { bgExpiry: "", POEndDate: "", NDays: "", bgExpiryHash: "" };
}

export const BGExpiryCheckRequest: MessageFns<BGExpiryCheckRequest> = {
  encode(message: BGExpiryCheckRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bgExpiry !== "") {
      writer.uint32(10).string(message.bgExpiry);
    }
    if (message.POEndDate !== "") {
      writer.uint32(18).string(message.POEndDate);
    }
    if (message.NDays !== "") {
      writer.uint32(26).string(message.NDays);
    }
    if (message.bgExpiryHash !== "") {
      writer.uint32(34).string(message.bgExpiryHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BGExpiryCheckRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBGExpiryCheckRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bgExpiry = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.POEndDate = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.NDays = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.bgExpiryHash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BGExpiryCheckRequest {
    return {
      bgExpiry: isSet(object.bgExpiry) ? globalThis.String(object.bgExpiry) : "",
      POEndDate: isSet(object.POEndDate) ? globalThis.String(object.POEndDate) : "",
      NDays: isSet(object.NDays) ? globalThis.String(object.NDays) : "",
      bgExpiryHash: isSet(object.bgExpiryHash) ? globalThis.String(object.bgExpiryHash) : "",
    };
  },

  toJSON(message: BGExpiryCheckRequest): unknown {
    const obj: any = {};
    if (message.bgExpiry !== "") {
      obj.bgExpiry = message.bgExpiry;
    }
    if (message.POEndDate !== "") {
      obj.POEndDate = message.POEndDate;
    }
    if (message.NDays !== "") {
      obj.NDays = message.NDays;
    }
    if (message.bgExpiryHash !== "") {
      obj.bgExpiryHash = message.bgExpiryHash;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BGExpiryCheckRequest>, I>>(base?: I): BGExpiryCheckRequest {
    return BGExpiryCheckRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BGExpiryCheckRequest>, I>>(object: I): BGExpiryCheckRequest {
    const message = createBaseBGExpiryCheckRequest();
    message.bgExpiry = object.bgExpiry ?? "";
    message.POEndDate = object.POEndDate ?? "";
    message.NDays = object.NDays ?? "";
    message.bgExpiryHash = object.bgExpiryHash ?? "";
    return message;
  },
};

function createBaseBGExpiryCheckResponse(): BGExpiryCheckResponse {
  return { success: false, message: "", isValid: false };
}

export const BGExpiryCheckResponse: MessageFns<BGExpiryCheckResponse> = {
  encode(message: BGExpiryCheckResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.isValid !== false) {
      writer.uint32(24).bool(message.isValid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BGExpiryCheckResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBGExpiryCheckResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isValid = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BGExpiryCheckResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      isValid: isSet(object.isValid) ? globalThis.Boolean(object.isValid) : false,
    };
  },

  toJSON(message: BGExpiryCheckResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.isValid !== false) {
      obj.isValid = message.isValid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BGExpiryCheckResponse>, I>>(base?: I): BGExpiryCheckResponse {
    return BGExpiryCheckResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BGExpiryCheckResponse>, I>>(object: I): BGExpiryCheckResponse {
    const message = createBaseBGExpiryCheckResponse();
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    message.isValid = object.isValid ?? false;
    return message;
  },
};

function createBaseAmountWithinRangeRequest(): AmountWithinRangeRequest {
  return { invoiceTotal: "", poBalance: "", poBalanceHash: "" };
}

export const AmountWithinRangeRequest: MessageFns<AmountWithinRangeRequest> = {
  encode(message: AmountWithinRangeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.invoiceTotal !== "") {
      writer.uint32(10).string(message.invoiceTotal);
    }
    if (message.poBalance !== "") {
      writer.uint32(18).string(message.poBalance);
    }
    if (message.poBalanceHash !== "") {
      writer.uint32(26).string(message.poBalanceHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AmountWithinRangeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAmountWithinRangeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.invoiceTotal = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.poBalance = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.poBalanceHash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AmountWithinRangeRequest {
    return {
      invoiceTotal: isSet(object.invoiceTotal) ? globalThis.String(object.invoiceTotal) : "",
      poBalance: isSet(object.poBalance) ? globalThis.String(object.poBalance) : "",
      poBalanceHash: isSet(object.poBalanceHash) ? globalThis.String(object.poBalanceHash) : "",
    };
  },

  toJSON(message: AmountWithinRangeRequest): unknown {
    const obj: any = {};
    if (message.invoiceTotal !== "") {
      obj.invoiceTotal = message.invoiceTotal;
    }
    if (message.poBalance !== "") {
      obj.poBalance = message.poBalance;
    }
    if (message.poBalanceHash !== "") {
      obj.poBalanceHash = message.poBalanceHash;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AmountWithinRangeRequest>, I>>(base?: I): AmountWithinRangeRequest {
    return AmountWithinRangeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AmountWithinRangeRequest>, I>>(object: I): AmountWithinRangeRequest {
    const message = createBaseAmountWithinRangeRequest();
    message.invoiceTotal = object.invoiceTotal ?? "";
    message.poBalance = object.poBalance ?? "";
    message.poBalanceHash = object.poBalanceHash ?? "";
    return message;
  },
};

function createBaseAmountWithinRangeResponse(): AmountWithinRangeResponse {
  return { success: false, message: "", isValid: false };
}

export const AmountWithinRangeResponse: MessageFns<AmountWithinRangeResponse> = {
  encode(message: AmountWithinRangeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.isValid !== false) {
      writer.uint32(24).bool(message.isValid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AmountWithinRangeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAmountWithinRangeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isValid = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AmountWithinRangeResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      isValid: isSet(object.isValid) ? globalThis.Boolean(object.isValid) : false,
    };
  },

  toJSON(message: AmountWithinRangeResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.isValid !== false) {
      obj.isValid = message.isValid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AmountWithinRangeResponse>, I>>(base?: I): AmountWithinRangeResponse {
    return AmountWithinRangeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AmountWithinRangeResponse>, I>>(object: I): AmountWithinRangeResponse {
    const message = createBaseAmountWithinRangeResponse();
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    message.isValid = object.isValid ?? false;
    return message;
  },
};

export type ZKPVerificationServiceService = typeof ZKPVerificationServiceService;
export const ZKPVerificationServiceService = {
  verifyClauseInclusion: {
    path: "/zkpVerification.ZKPVerificationService/VerifyClauseInclusion",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: VerifyClauseInclusionRequest): Buffer =>
      Buffer.from(VerifyClauseInclusionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): VerifyClauseInclusionRequest => VerifyClauseInclusionRequest.decode(value),
    responseSerialize: (value: VerifyClauseInclusionResponse): Buffer =>
      Buffer.from(VerifyClauseInclusionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): VerifyClauseInclusionResponse => VerifyClauseInclusionResponse.decode(value),
  },
  bgExpiryCheck: {
    path: "/zkpVerification.ZKPVerificationService/BGExpiryCheck",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: BGExpiryCheckRequest): Buffer => Buffer.from(BGExpiryCheckRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): BGExpiryCheckRequest => BGExpiryCheckRequest.decode(value),
    responseSerialize: (value: BGExpiryCheckResponse): Buffer =>
      Buffer.from(BGExpiryCheckResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BGExpiryCheckResponse => BGExpiryCheckResponse.decode(value),
  },
  amountWithinRange: {
    path: "/zkpVerification.ZKPVerificationService/AmountWithinRange",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AmountWithinRangeRequest): Buffer =>
      Buffer.from(AmountWithinRangeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AmountWithinRangeRequest => AmountWithinRangeRequest.decode(value),
    responseSerialize: (value: AmountWithinRangeResponse): Buffer =>
      Buffer.from(AmountWithinRangeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AmountWithinRangeResponse => AmountWithinRangeResponse.decode(value),
  },
} as const;

export interface ZKPVerificationServiceServer extends UntypedServiceImplementation {
  verifyClauseInclusion: handleUnaryCall<VerifyClauseInclusionRequest, VerifyClauseInclusionResponse>;
  bgExpiryCheck: handleUnaryCall<BGExpiryCheckRequest, BGExpiryCheckResponse>;
  amountWithinRange: handleUnaryCall<AmountWithinRangeRequest, AmountWithinRangeResponse>;
}

export interface ZKPVerificationServiceClient extends Client {
  verifyClauseInclusion(
    request: VerifyClauseInclusionRequest,
    callback: (error: ServiceError | null, response: VerifyClauseInclusionResponse) => void,
  ): ClientUnaryCall;
  verifyClauseInclusion(
    request: VerifyClauseInclusionRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: VerifyClauseInclusionResponse) => void,
  ): ClientUnaryCall;
  verifyClauseInclusion(
    request: VerifyClauseInclusionRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: VerifyClauseInclusionResponse) => void,
  ): ClientUnaryCall;
  bgExpiryCheck(
    request: BGExpiryCheckRequest,
    callback: (error: ServiceError | null, response: BGExpiryCheckResponse) => void,
  ): ClientUnaryCall;
  bgExpiryCheck(
    request: BGExpiryCheckRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: BGExpiryCheckResponse) => void,
  ): ClientUnaryCall;
  bgExpiryCheck(
    request: BGExpiryCheckRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: BGExpiryCheckResponse) => void,
  ): ClientUnaryCall;
  amountWithinRange(
    request: AmountWithinRangeRequest,
    callback: (error: ServiceError | null, response: AmountWithinRangeResponse) => void,
  ): ClientUnaryCall;
  amountWithinRange(
    request: AmountWithinRangeRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AmountWithinRangeResponse) => void,
  ): ClientUnaryCall;
  amountWithinRange(
    request: AmountWithinRangeRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AmountWithinRangeResponse) => void,
  ): ClientUnaryCall;
}

export const ZKPVerificationServiceClient = makeGenericClientConstructor(
  ZKPVerificationServiceService,
  "zkpVerification.ZKPVerificationService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): ZKPVerificationServiceClient;
  service: typeof ZKPVerificationServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
