// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.32.1
// source: zkpVerification.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "zkpVerification";

export interface VerifyClauseInclusionRequest {
  agreementId: string;
  clauseSetHash: string;
  commitment: string;
}

export interface VerifyClauseInclusionResponse {
  success: boolean;
  message: string;
  isValid: boolean;
}

function createBaseVerifyClauseInclusionRequest(): VerifyClauseInclusionRequest {
  return { agreementId: "", clauseSetHash: "", commitment: "" };
}

export const VerifyClauseInclusionRequest: MessageFns<VerifyClauseInclusionRequest> = {
  encode(message: VerifyClauseInclusionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.agreementId !== "") {
      writer.uint32(10).string(message.agreementId);
    }
    if (message.clauseSetHash !== "") {
      writer.uint32(18).string(message.clauseSetHash);
    }
    if (message.commitment !== "") {
      writer.uint32(26).string(message.commitment);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyClauseInclusionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyClauseInclusionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.agreementId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clauseSetHash = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.commitment = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VerifyClauseInclusionRequest {
    return {
      agreementId: isSet(object.agreementId) ? globalThis.String(object.agreementId) : "",
      clauseSetHash: isSet(object.clauseSetHash) ? globalThis.String(object.clauseSetHash) : "",
      commitment: isSet(object.commitment) ? globalThis.String(object.commitment) : "",
    };
  },

  toJSON(message: VerifyClauseInclusionRequest): unknown {
    const obj: any = {};
    if (message.agreementId !== "") {
      obj.agreementId = message.agreementId;
    }
    if (message.clauseSetHash !== "") {
      obj.clauseSetHash = message.clauseSetHash;
    }
    if (message.commitment !== "") {
      obj.commitment = message.commitment;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VerifyClauseInclusionRequest>, I>>(base?: I): VerifyClauseInclusionRequest {
    return VerifyClauseInclusionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyClauseInclusionRequest>, I>>(object: I): VerifyClauseInclusionRequest {
    const message = createBaseVerifyClauseInclusionRequest();
    message.agreementId = object.agreementId ?? "";
    message.clauseSetHash = object.clauseSetHash ?? "";
    message.commitment = object.commitment ?? "";
    return message;
  },
};

function createBaseVerifyClauseInclusionResponse(): VerifyClauseInclusionResponse {
  return { success: false, message: "", isValid: false };
}

export const VerifyClauseInclusionResponse: MessageFns<VerifyClauseInclusionResponse> = {
  encode(message: VerifyClauseInclusionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.isValid !== false) {
      writer.uint32(24).bool(message.isValid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyClauseInclusionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyClauseInclusionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isValid = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VerifyClauseInclusionResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      isValid: isSet(object.isValid) ? globalThis.Boolean(object.isValid) : false,
    };
  },

  toJSON(message: VerifyClauseInclusionResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.isValid !== false) {
      obj.isValid = message.isValid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VerifyClauseInclusionResponse>, I>>(base?: I): VerifyClauseInclusionResponse {
    return VerifyClauseInclusionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyClauseInclusionResponse>, I>>(
    object: I,
  ): VerifyClauseInclusionResponse {
    const message = createBaseVerifyClauseInclusionResponse();
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    message.isValid = object.isValid ?? false;
    return message;
  },
};

export type ZKPVerificationServiceService = typeof ZKPVerificationServiceService;
export const ZKPVerificationServiceService = {
  verifyClauseInclusion: {
    path: "/zkpVerification.ZKPVerificationService/VerifyClauseInclusion",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: VerifyClauseInclusionRequest): Buffer =>
      Buffer.from(VerifyClauseInclusionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): VerifyClauseInclusionRequest => VerifyClauseInclusionRequest.decode(value),
    responseSerialize: (value: VerifyClauseInclusionResponse): Buffer =>
      Buffer.from(VerifyClauseInclusionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): VerifyClauseInclusionResponse => VerifyClauseInclusionResponse.decode(value),
  },
} as const;

export interface ZKPVerificationServiceServer extends UntypedServiceImplementation {
  verifyClauseInclusion: handleUnaryCall<VerifyClauseInclusionRequest, VerifyClauseInclusionResponse>;
}

export interface ZKPVerificationServiceClient extends Client {
  verifyClauseInclusion(
    request: VerifyClauseInclusionRequest,
    callback: (error: ServiceError | null, response: VerifyClauseInclusionResponse) => void,
  ): ClientUnaryCall;
  verifyClauseInclusion(
    request: VerifyClauseInclusionRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: VerifyClauseInclusionResponse) => void,
  ): ClientUnaryCall;
  verifyClauseInclusion(
    request: VerifyClauseInclusionRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: VerifyClauseInclusionResponse) => void,
  ): ClientUnaryCall;
}

export const ZKPVerificationServiceClient = makeGenericClientConstructor(
  ZKPVerificationServiceService,
  "zkpVerification.ZKPVerificationService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): ZKPVerificationServiceClient;
  service: typeof ZKPVerificationServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
